const { defineConfig } = require('eslint-define-config');

module.exports = defineConfig({
  root: true,
  plugins: ['@typescript-eslint', 'prettier', 'unicorn'],
  extends: [
    '.eslintrc-auto-import.json',
    'eslint:recommended',
    'airbnb-base',
    'plugin:@typescript-eslint/recommended',
    'plugin:vue/vue3-recommended',
    'prettier',
  ],
  parserOptions: {
    parser: '@typescript-eslint/parser',
    ecmaVersion: 2020,
    sourceType: 'module',
    extraFileExtensions: ['.vue'],
    ecmaFeatures: {
      jsx: true,
    },
  },
  env: {
    browser: true,
    es6: true,
    node: true,
    'vue/setup-compiler-macros': true,
  },
  overrides: [
    {
      files: ['*.vue'],
      rules: {
        'no-undef': 'off',
      },
    },
  ],
  rules: {
    'prettier/prettier': 'error',
    'no-console': ['warn', { allow: ['error'] }],
    'no-empty': ['error', { allowEmptyCatch: true }],
    'no-unused-vars': 'off',
    'no-var': 'warn',
    'no-restricted-syntax': 'off',
    'no-param-reassign': 'off',
    'no-plusplus': 'off',
    'no-shadow': 'off',
    'no-use-before-define': 'off',
    'no-underscore-dangle': 'off',
    'no-multi-assign': 'off',
    'no-undef': 'off',
    'vue/html-closing-bracket-newline': 'warn',
    'vue/multi-word-component-names': 'off',
    'vue/no-deprecated-html-element-is': 'off',
    'vue/require-component-is': 'off',
    'vue/require-default-prop': 'off',
    'vue/v-on-event-hyphenation': 'off',
    'vue/no-v-html': 'off',
    'vue/require-prop-types': 'off',
    'vue/html-self-closing': [
      'error',
      {
        html: {
          void: 'always',
        },
      },
    ],
    'vue/component-name-in-template-casing': [
      'error',
      'PascalCase',
      {
        registeredComponentsOnly: false,
        ignores: [],
      },
    ],
    'import/no-dynamic-require': 'off',
    'import/no-import-module-exports': 'off',
    'import/no-unresolved': 'off',
    'import/extensions': 'off',
    'import/prefer-default-export': 'off',
    'import/no-extraneous-dependencies': 'off',
    'typescript-eslint/ban-types': 'off',
    '@typescript-eslint/semi': 'error',
    '@typescript-eslint/no-inferrable-types': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-shadow': 'error',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-empty-interface': 'off',
    '@typescript-eslint/no-non-null-assertion': 'off',
    '@typescript-eslint/ban-types': 'off',
    '@typescript-eslint/no-var-requires': 'off',
    '@typescript-eslint/ban-ts-comment': 'off',
    'default-case': 'off',
    'global-require': 'off',
    'prefer-const': 'error',
    'guard-for-in': 'off',
    'next-line': 'off',
    'class-methods-use-this': 'off',
    'unicorn/prefer-node-protocol': 'error',
  },
});
